# 중복제거 안된 24시간 데이터 전처리

In [2]:
import pandas as pd
import os
import datetime
from statsmodels.formula.api import ols
from matplotlib import rc

In [27]:
pd.options.display.max_colwidth = 1000

# 전처리

## 0928

In [7]:
path = './전처리/0928/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

In [11]:
df = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df = pd.concat([df,data])
    
df = df.reset_index(drop = True)

In [12]:
df

,num,region,title,category,time,price,detail,interest,chat,view
0,289502961,도봉구 도봉제2동,cj제일제당 선물세트,생활/가공식품,5일 전,15000,3세트 있어요. 한세트당 가격입니다.\n스팸6개 해바라기씨유 2개 들어 있어요\n가...,1,0,92
1,287598338,도봉구 창제1동,(미개봉새상품) DUNLOP 남성 스킨로션 선물세트,뷰티/미용,11일 전,10000,"박스채 그대로 미개봉 새상품 남성 스킨 로션 선물세트입니다,\n용량은 본품 각 15...",1,1,60
2,286049252,도봉구 창제5동,롯데 수제명작 수제햄 선물세트,생활/가공식품,14일 전,35000,명절 선물로 좋은 수제햄 선물세트 입니다\n인터넷 최저가 보다 훨씬 싸게 내놓아요\...,3,1,220
3,287506463,도봉구 창동,"스팸8호 선물세트 ( 개봉상품, 쇼핑백있음)",생활/가공식품,11일 전,19000,- 신창아파트 근처~녹천역\n쇼핑백 있음.\n스티커 개봉 상품으로 사진과 같이 박스...,5,2,239
4,286367303,도봉구 방학제1동,[미개봉 새제품] 정관장 선물세트 다보록 여유담편,생활/가공식품,끌올 12일 전,75000,정관장 추석 선물세트가 들어왔는데 저희가족 모두 홍삼을 별로 안 좋아해서 당근합니다...,2,1,289
...,...,...,...,...,...,...,...,...,...,...
6005,288648127,양천구 목2동,추석선물 일품진성 홍삼세트,생활/가공식품,7일 전,35000,새상품입니다\n쇼핑백형태로 선물하기 좋습니당!\n가격 많이 내렸습니당,3,1,123
6006,289269423,양천구 신정6동,테소리 도리엔테 2종 선물세트(미개봉),뷰티/미용,끌올 1일 전,40000,테소리 도리엔테 (함맘)\n2종 선물세트\n바디워시250ml+바디크림300ml+샤워볼,1,0,6
6007,288808580,양천구 신정6동,청정원 햄 선물세트 판매합니다.,생활/가공식품,끌올 5일 전,15000,햄을 좋아하는 사람이 없어서 선물세트 판매합니다.\n생각보다 무거워서 목동중 앞까지...,8,0,466
6008,289761109,양천구 신월2동,스팸 선물세트 1만8천원,생활/가공식품,5일 전,18000,새상품인데 상자앞쪽에 약간찍힘있네요\n스팸클래식 200g 9개 유통기한 24년 7월...,5,4,274
6009,287934495,양천구 목2동,중국 월병 추석선물세트 11개입,생활/가공식품,10일 전,20000,중국에서 추석때 월병을 먹는다고 해요~\n한개가 커서 1개만 먹어도 배불러요 ㅎㅎ,1,1,117

In [19]:
df['date'] = '210928'
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6010 entries, 0 to 6009
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   num       6010 non-null   int64
 1   region    6010 non-null   object
 2   title     6010 non-null   object
 3   category  6010 non-null   object
 4   time      6010 non-null   object
 5   price     6010 non-null   int64
 6   detail    5994 non-null   object
 7   interest  6010 non-null   int64
 8   chat      6010 non-null   int64
 9   view      6010 non-null   int64
 10  date      6010 non-null   object
dtypes: int64(5), object(6)
memory usage: 563.4+ KB

In [20]:
df['date']=pd.to_datetime(df['date'], format="%y%m%d")

In [22]:
df.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,289502961,도봉구 도봉제2동,cj제일제당 선물세트,생활/가공식품,5일 전,15000,3세트 있어요. 한세트당 가격입니다.\n스팸6개 해바라기씨유 2개 들어 있어요\n가...,1,0,92,2021-09-28
1,287598338,도봉구 창제1동,(미개봉새상품) DUNLOP 남성 스킨로션 선물세트,뷰티/미용,11일 전,10000,"박스채 그대로 미개봉 새상품 남성 스킨 로션 선물세트입니다,\n용량은 본품 각 15...",1,1,60,2021-09-28

In [23]:
df.to_csv('./seoul_210928_date.csv',encoding='utf-8-sig')

## 0929

In [24]:
path = './전처리/0929/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

In [25]:
df29 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df29 = pd.concat([df29,data])
    
df29 = df29.reset_index(drop = True)

In [26]:
df29

,num,region,title,category,time,price,detail,interest,chat,view
0,281728179,구로구 신도림동,양키캔들 선물세트,생활/가공식품,끌올 22시간 전,20000,"양키캔들 블랙체리 향,\n모자이크 자쉐이드 (가로21 세로13 높이11) 입니다",4,0,473
1,286132961,구로구 구로동,임실치즈 선물세트,생활/가공식품,끌올 4일 전,48000,구로역 직거래 가능하고 쇼핑백도 있어요,9,2,683
2,290253446,구로구 오류제1동,동원.건겅한2호..선물..세트,생활/가공식품,끌올 2일 전,38000,"최저가.1개당.28,800원자리\n2개판매합니다\n추석선물로받았는데..저한텐필요없어...",1,1,87
3,291635384,구로구 개봉제3동,청정원 선물세트,생활/가공식품,1일 전,19000,추석때 선물로 받은 \n청정원 복합 선물세트 입니다.\n구성도 알차게 들어가 있어서...,3,0,50
4,287004036,구로구 구로동,선물세트 동원 스페셜 24호 팝니다,생활/가공식품,끌올 2일 전,33000,"동원 스페셜 24호 팝니다\n사진만 찍고 바로 닫은 상품입니다\n신도림역 2,3번 ...",6,2,295
...,...,...,...,...,...,...,...,...,...,...
4195,286906186,관악구 신림동,설화수 2종 선물세트. 미개봉 새상품,뷰티/미용,끌올 10시간 전,68000,신림역 직거래 또는 반값택배가능\n쇼핑백 같이 드려요\n,6,0,200
4196,188952648,관악구 봉천동,벨라수 선물세트+클렌져,뷰티/미용,끌올 2시간 전,10000,벨라수 기린V리프팅 마스크\n벨라수 기린넥프팅크림\n클리덤 닥터락토 수딩젤 클렌징폼...,1,0,99
4197,287859962,관악구 봉천동,동원참치선물셋트,생활/가공식품,끌올 22시간 전,28000,15그램 선물하세요,12,4,966
4198,285173959,관악구 행운동,(새상품) 미샤 고급 한방라인 기초화장품\n초공진 영안 3종세트 선물세트,뷰티/미용,끌올 2일 전,49000,(새상품) 미샤 고급 한방라인 기초화장품\n초공진 영안 3종 리미티드 기초 세트에요...,3,2,31
4199,258465109,관악구 청림동,프레쉬 핸드크림+립밤세트 (선물포장 o) / 가격내림,뷰티/미용,끌올 2일 전,13000,"프레쉬 핸드크림+립밤세트입니다.\n친구 선물 주려고 샀는데, \n배송지 입력을 저희...",7,1,214

In [33]:
df29['date'] = '210929'
df29['date']=pd.to_datetime(df29['date'], format="%y%m%d")

In [34]:
df29.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,281728179,구로구 신도림동,양키캔들 선물세트,생활/가공식품,끌올 22시간 전,20000,"양키캔들 블랙체리 향,\n모자이크 자쉐이드 (가로21 세로13 높이11) 입니다",4,0,473,2021-09-29
1,286132961,구로구 구로동,임실치즈 선물세트,생활/가공식품,끌올 4일 전,48000,구로역 직거래 가능하고 쇼핑백도 있어요,9,2,683,2021-09-29

In [35]:
df29.to_csv('./seoul_210929_date.csv',encoding='utf-8-sig')

## 0930

In [30]:
path = './전처리/0930/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

In [31]:
df30 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df30 = pd.concat([df30,data])
    
df30 = df30.reset_index(drop = True)

In [32]:
df30

,num,region,title,category,time,price,detail,interest,chat,view
0,285908256,성북구 하월곡동,블랙라벨 T호 스팸 명절 선물세트,생활/가공식품,끌올 11일 전,39000,방금 마트에서 56000원 주고 산 선물세트입니다.\n스팸 12개+안달루시안산 올리...,3,2,679
1,288921368,성북구 장위동,한우 소고기 선물세트 1.4kg,생활/가공식품,8일 전,100000,농협안심한우 소한마리 한우선물세트 \n카카오톡 선물하기로 받은거구요\n현재 배송대기...,10,3,703
2,285663874,성북구 정릉동,버츠비 선물 세트 미사용 새제품,뷰티/미용,끌올 20시간 전,10000,비대면 거래 선호해용,6,1,157
3,272099415,성북구 길음동,프로바이오틱스 석류콜라겐 원액 2병 선물세트,생활/가공식품,끌올 4일 전,15000,프로바이오틱스 함유 석류콜라겐 \n750ml짜리 2병 선물세트입니다\n(전용 쇼핑...,-2,2,62
4,288967520,성북구 삼선동,후레쉬 프리미엄 오일 선물세트,생활/가공식품,끌올 3일 전,10000,선물받은상태인데 박스에 글자가써있어요\n집에 소금많아서 판매합니다\n삼선동 성북세무...,12,2,359
...,...,...,...,...,...,...,...,...,...,...
4231,286262534,금천구 독산동,(추석선물세트) CJ제일제당 현명한선택E호(구 CJ현명한선택6호) 스팸/해바라기씨유...,생활/가공식품,끌올 2일 전,26000,당연히 미개봉상품이며 실사진은 요청하면 보여드립니다\n즐거운 한가위 보내세요\n우리...,-1,1,32
4232,286314154,금천구 가산동,[미개봉 초특가] lg생활건강 생활의 품격 24호 선물세트,뷰티/미용,끌올 3일 전,12000,[미개봉 초특가] 생활의 품격 24호\nLG생활건강 선물세트 인터넷 최저가보다 싸게...,6,1,174
4233,287350769,금천구 독산동,"백설 식용유, 올리고당, 식초 선물세트",생활/가공식품,끌올 2일 전,10000,"백설 식용유, 올리고당, 식초 선물세트 판매합니다.",4,0,470
4234,287182877,금천구 시흥제2동,LG 생활건강 히말라야 핑크솔트 펌핑치약 선물세트,생활/가공식품,끌올 9일 전,20000,프리미엄 히말라야 핑크솔트 펌핑치약 선물세트\n미개봉 새상품입니다,4,5,344
4235,288122954,금천구 시흥제1동,엘지생활 선물세트,생활/가공식품,끌올 3일 전,30000,#선물세트\n#엘지생활건강\n#엘지43호,0,0,145

In [37]:
df30['date'] = '210930'
df30['date']=pd.to_datetime(df30['date'], format="%y%m%d")

In [38]:
df30.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,285908256,성북구 하월곡동,블랙라벨 T호 스팸 명절 선물세트,생활/가공식품,끌올 11일 전,39000,방금 마트에서 56000원 주고 산 선물세트입니다.\n스팸 12개+안달루시안산 올리...,3,2,679,2021-09-30
1,288921368,성북구 장위동,한우 소고기 선물세트 1.4kg,생활/가공식품,8일 전,100000,농협안심한우 소한마리 한우선물세트 \n카카오톡 선물하기로 받은거구요\n현재 배송대기...,10,3,703,2021-09-30

In [39]:
df30.to_csv('./seoul_210930_date.csv',encoding='utf-8-sig')

## 1001

In [40]:
path = './전처리/1001/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

df01 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df01 = pd.concat([df01,data])
    
df01 = df01.reset_index(drop = True)

In [41]:
df01

,num,region,title,category,time,price,detail,interest,chat,view
0,286988744,강북구 수유3동,동원 선물세트 99-R호 팔아요(새제품),생활/가공식품,끌올 5일 전,30000,이번 추석선물로 받은거라 유통기한 넉넉해요,4,0,412
1,287973377,강북구 번1동,특 프리미엄 사과 선물세트 추석선물 명절,생활/가공식품,12일 전,35000,쿨거래 환영\n과일이 많아 판매합니다,1,1,145
2,286826259,강북구 번2동,투썸 스페셜 기프트세트 선물세트,생활/가공식품,끌올 4일 전,10000,10000원에 판매합니다 \n직거래는 번2동이나 미아사거리역2번출구입니다 \n평일은...,6,2,382
3,292100762,강북구 미아동,명절에받은새상품선물세트,생활/가공식품,3일 전,22000,연락주세요,4,0,34
4,286501212,강북구 수유동,수삼 허니셋트 (명절 선물용),생활/가공식품,끌올 12일 전,40000,안녕하세용\n지인분 통해 선물 받았는데...\n전 안먹어서;;; \n네이버에 수삼 ...,8,3,247
...,...,...,...,...,...,...,...,...,...,...
3075,280506381,종로구 계동,시슬리 향수 바디크림 선물세트,뷰티/미용,끌올 11일 전,90000,선물용으로도 좋아요~~,1,4,173
3076,289553475,종로구 숭인동,(새상품*선물세트)키엘 핸드크림,뷰티/미용,끌올 3일 전,17000,"카톡선물하기로 받았는데\n핸드크림 넘쳐나서\n저렴히 판매해요ㅜㅜ\n동묘역, 시청역 ...",1,0,21
3077,280994419,종로구 동숭동,아기 새옷) 출산 선물세트,유아동,끌올 21시간 전,25000,선물 받은 박스 그대로..\n아기긴팔 바디수트 80호. 속싸개. 손수건. 손싸개 . 양말,4,0,123
3078,287539183,종로구 원서동,선물세트 광천김,생활/가공식품,끌올 7일 전,10000,회사에서 받은 광천 어머니김 선물세트 한박스\n판매합니다,12,2,325
3079,282718797,종로구 옥인동,LG생활건강 선물세트,생활/가공식품,끌올 16일 전,15000,봉투있어요,3,1,215

In [43]:
df01['date'] = '211001'
df01['date']=pd.to_datetime(df01['date'], format="%y%m%d")
df01.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,286988744,강북구 수유3동,동원 선물세트 99-R호 팔아요(새제품),생활/가공식품,끌올 5일 전,30000,이번 추석선물로 받은거라 유통기한 넉넉해요,4,0,412,2021-10-01
1,287973377,강북구 번1동,특 프리미엄 사과 선물세트 추석선물 명절,생활/가공식품,12일 전,35000,쿨거래 환영\n과일이 많아 판매합니다,1,1,145,2021-10-01

In [44]:
df01.to_csv('./seoul_211001_date.csv',encoding='utf-8-sig')

## 1002

In [46]:
path = './전처리/1002/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

df02 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df02 = pd.concat([df02,data])
    
df02 = df02.reset_index(drop = True)
df02

,num,region,title,category,time,price,detail,interest,chat,view
0,291582404,마포구 성산동,한과선물세트2단(새상품),생활/가공식품,5일 전,22000,(유통기한 - 2022년1월10일)\n(쇼핑백 X)\n쇼핑백을 못찾아서 박스만 들고...,0,1,91
1,291871893,마포구 동교동,"독일제 스테인리스 수통 플라스크 선물세트 위스키, 보드카 등",남성패션/잡화,4일 전,50000,독일에서 구입한 스테인리스 수통입니다. \n한 손에 딱 잡히는 사이즈 입니다.,2,0,77
2,289780760,마포구 대흥동,[선물세트] 샹달프 잼 4종 세트(284g*4개),생활/가공식품,끌올 6일 전,15000,샹달프 잼 4종 세트(284g*4개) 선물용으로도 좋습니다\n블루베리/딸기/금귤/무...,7,1,173
3,286327521,마포구 합정동,드리오 녹용홍삼진액 선물세트 새제품 쇼핑백포함,생활/가공식품,끌올 9시간 전,45000,👉🏻새제품에 쇼핑백까지 있습니다 \n👉🏻선물세트로 좋습니다\n👉🏻실 판매 79000...,0,0,29
4,291590476,마포구 상암동,선물 세트 여러가지,기타 중고물품,5일 전,30000,박스와 쇼핑백 그대로입니다.\n너무 많아서 판매합니다.,9,2,285
...,...,...,...,...,...,...,...,...,...,...
3050,293407293,동작구 사당제2동,타이틀리스트 골프공&지갑 선물세트,스포츠/레저,14시간 전,30000,***-****-**** \n택배비 0.35~0.4추가\n반값택배 0.16~0.2...,1,0,48
3051,288450640,동작구 대방동,동원 선물세트,생활/가공식품,끌올 22시간 전,26900,"남도학숙 공군회관 대방역2번 출구 직거래 희망합니다. :)\n 새거라서 교환, 환불...",7,1,294
3052,293094065,동작구 사당제5동,쟈뎅 프리미엄 선물셋트 판매해요,생활/가공식품,1일 전,25000,2022.6.22\n남성역 거래원해요,3,0,78
3053,287910222,동작구 노량진동,cj 현명한선택 f호 선물세트,생활/가공식품,끌올 3일 전,20000,쌍용예가 or 강남교회 직거래,5,0,294
3054,278687654,동작구 사당동,[새상품] 오설록 선물세트,생활/가공식품,끌올 2일 전,12000,* 구매하실 분만 연락주세요,12,0,587

In [47]:
df02['date'] = '211002'
df02['date']=pd.to_datetime(df02['date'], format="%y%m%d")
df02.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,291582404,마포구 성산동,한과선물세트2단(새상품),생활/가공식품,5일 전,22000,(유통기한 - 2022년1월10일)\n(쇼핑백 X)\n쇼핑백을 못찾아서 박스만 들고...,0,1,91,2021-10-02
1,291871893,마포구 동교동,"독일제 스테인리스 수통 플라스크 선물세트 위스키, 보드카 등",남성패션/잡화,4일 전,50000,독일에서 구입한 스테인리스 수통입니다. \n한 손에 딱 잡히는 사이즈 입니다.,2,0,77,2021-10-02

In [48]:
df02.to_csv('./seoul_211002_date.csv',encoding='utf-8-sig')

## 1003

In [49]:
path = './전처리/1003/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

df03 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df03 = pd.concat([df03,data])
    
df03 = df03.reset_index(drop = True)
df03

,num,region,title,category,time,price,detail,interest,chat,view
0,286628166,관악구 봉천동,오뚜기 선물세트 팝니당,생활/가공식품,끌올 2일 전,8000,유통기한 23.07.01,5,0,225
1,269067598,관악구 신원동,보온병 선물세트 2종 새상품,생활/가공식품,끌올 1일 전,15000,500미리 두개 들어있는 텀블러 선물세트에요\n남서울중학교 직거래,17,3,820
2,293053719,관악구 봉천동,바디판타지 선물세트 미개봉 - 피치 애프리콧,뷰티/미용,3일 전,15000,바디판타지 박스에 포장된 선물세트입니다!,1,0,42
3,256465458,관악구 신원동,알프스 면기세트 선물용 새상품,생활/가공식품,끌올 2일 전,25000,선물가능 새상품\n사진만 찍고 보관중\n저렴하게 가져가세요\n약 15*7 사이즈\n...,4,2,862
4,293389549,관악구 신원동,(새제품) 탬버린즈 핸드크림 손소독제 선물세트,뷰티/미용,2일 전,20000,탬버린즈 핸드크림 손소독제 선물세트 팔아요 :) \n선물하실수 있게 카드까지 구성품...,1,0,90
...,...,...,...,...,...,...,...,...,...,...
3039,216475514,성북구 보문동2가,<새제품>우드윅 향초 미니워머 선물세트,가구/인테리어,끌올 3일 전,27000,선물받은 새상품이예요\n뽁뽁이까지 그대로 세워두고 보관중\n사진찍으려고 열어봅니다^^,6,0,324
3040,284796568,성북구 길음제1동,💓성찬식품 누룽지 선물 세트 A 판매💓,생활/가공식품,끌올 5일 전,35000,성찬식품 우리쌀 100%로 만든 누룽지 선물세트입니다~ 지인에게 어제 선물 받았는데...,6,2,359
3041,291203063,성북구 삼선동1가,lg생활건강 선물세트,뷰티/미용,7일 전,5000,쇼핑몰에서 6000원대 판매하고 있는 상품입니다\n한성대입구역 3번 출구에서 거래합니다,0,2,25
3042,289695732,성북구 상월곡동,선물세트 동원스페셜 3호 급처,생활/가공식품,끌올 1일 전,10000,선물받았습니다.,5,3,549
3043,286633991,성북구 종암동,CJ제일제당 스팸 고급유 108호 선물세트,기타 중고물품,끌올 3일 전,25000,종암동 숭례초 정문 직거래,1,0,249

In [50]:
df03['date'] = '211003'
df03['date']=pd.to_datetime(df03['date'], format="%y%m%d")
df03.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,286628166,관악구 봉천동,오뚜기 선물세트 팝니당,생활/가공식품,끌올 2일 전,8000,유통기한 23.07.01,5,0,225,2021-10-03
1,269067598,관악구 신원동,보온병 선물세트 2종 새상품,생활/가공식품,끌올 1일 전,15000,500미리 두개 들어있는 텀블러 선물세트에요\n남서울중학교 직거래,17,3,820,2021-10-03

In [51]:
df03.to_csv('./seoul_211003_date.csv',encoding='utf-8-sig')

## 1004

In [53]:
path = './전처리/1004/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

df04 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df04 = pd.concat([df04,data])
    
df04 = df04.reset_index(drop = True)
df04

,num,region,title,category,time,price,detail,interest,chat,view
0,293393317,노원구 상계10동,프리미엄 함초 소금 세트 새상품 (선물용),생활/가공식품,끌올 14시간 전,20000,함초 소금 세트입니다. \n인터넷 최저가 37000원정도 하네요. \n새상품이고 선...,4,0,99
1,291206282,노원구 중계4동,(새상품) 버츠비 핸드크림+립밤 선물세트,뷰티/미용,끌올 4일 전,5000,"많이 저렴하게 내놔서 네고는 안됩니다~~ \n\n직거래는 중계벽산3차, 택배는 구매...",2,0,81
2,236957538,노원구 월계동,더바디샵 브리티쉬로즈 선물세트 판매합니다,뷰티/미용,끌올 4일 전,19000,더바디샵 브리티쉬로즈 선물세트 판매합니다\n선물받고 한 번도 사용안했습니다\n광운대...,3,1,215
3,292518843,노원구 공릉동,"스팸,참치 선물세트",생활/가공식품,끌올 2일 전,20000,추석에 들어온거라 유통기한 넉넉합니다.\n반품X,15,2,340
4,288488928,노원구 월계2동,동원 선물세트 64R호,생활/가공식품,끌올 9시간 전,23000,참치 고추참치 리챔으로 구성된 명절세트 선물입니다\n오늘 선물받은 새 상품입니다.!...,6,1,287
...,...,...,...,...,...,...,...,...,...,...
3033,290919123,중랑구 상봉제2동,광천김 선물세트 27봉,생활/가공식품,끌올 4일 전,9000,광천김 선물세트 \n유통기한 - 2022.07.09,10,5,236
3034,291408714,중랑구 묵제1동,스팸 마일드 8호 선물세트,생활/가공식품,7일 전,19000,스팸 선물세트 미개봉 팝니다\n직거래 가능합니다,0,2,196
3035,277975369,중랑구 상봉동,천종산삼배양근 선물세트💪,생활/가공식품,끌올 1일 전,27000,택배로 선물받은 제품입니다.\n집에드실분이 없네요~\n쇼핑백도있어서 선물하실분들 좋...,6,0,261
3036,291457056,중랑구 상봉제1동,목우촌 선물세트,생활/가공식품,끌올 5일 전,20000,사진으로 구성 확인해주세요~\n선물들어온건데 필요없어서 판매해요\n쇼핑백 한쪽에 스...,1,1,158
3037,288118844,중랑구 면목동,[새제품]아모레퍼시픽 희망가득 기프트 선물세트,뷰티/미용,끌올 5일 전,30000,아모레퍼시픽 희망가득 기프트 선물세트 입니다.\n제품 상세정보는 아래 링크를 참고하...,7,0,143

In [54]:
df04['date'] = '211004'
df04['date']=pd.to_datetime(df04['date'], format="%y%m%d")
df04.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,293393317,노원구 상계10동,프리미엄 함초 소금 세트 새상품 (선물용),생활/가공식품,끌올 14시간 전,20000,함초 소금 세트입니다. \n인터넷 최저가 37000원정도 하네요. \n새상품이고 선...,4,0,99,2021-10-04
1,291206282,노원구 중계4동,(새상품) 버츠비 핸드크림+립밤 선물세트,뷰티/미용,끌올 4일 전,5000,"많이 저렴하게 내놔서 네고는 안됩니다~~ \n\n직거래는 중계벽산3차, 택배는 구매...",2,0,81,2021-10-04

In [55]:
df04.to_csv('./seoul_211004_date.csv',encoding='utf-8-sig')

## 1005

In [389]:
path = './전처리/1005/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

df05 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df05 = pd.concat([df05,data])
    
df05 = df05.reset_index(drop = True)
df05

,num,region,title,category,time,price,detail,interest,chat,view
0,284578634,동작구 흑석동,키엘 포맨 선물세트,남성패션/잡화,끌올 2일 전,45000,선물 받았는데 쓰는 제품이 있어서 판매합니다\n훼이셜 퓨얼 에너자이징 토닉250 ml\n모이스쳐라이져 트리트먼트 포 맨 75ml\n증정품2개,4,0,92
1,291941854,동작구 사당동,뉴트리라이트 더블엑스 선물세트,생활/가공식품,끌올 4일 전,120000,본품1 리필1로 구성된 선물세트로 정가 167000원이네요\n명절선물로 받았는데 먹는 영양제가 많아 내놓아요\n뉴트리라이트 종이백도 같이있어 선물용으로도 좋아요 ^^\n아시는분들은 아시는 고급영양제 더블엑스 저렴하게 데려가세요,2,1,76
2,274614094,동작구 사당동,록시땅 선물세트,뷰티/미용,끌올 4일 전,17000,"선물받은 상태 그대로 보관중이에요 :)\n직거래위치 낙성대역, 교체어린이공원\n가능합니다😇⭐️",9,1,450
3,289733436,동작구 노량진동,선물세트 현명한선택 e호 스팸,생활/가공식품,끌올 1일 전,20000,미개봉 선물세트입니다,5,0,238
4,287389191,동작구 사당동,버블 핸드워시 선물세트,생활/가공식품,끌올 3일 전,20000,회사에서 선물받았는데 쓰지 않아 올리게되었습니다~ 사당 이수에서 직거래해요!!\n쿠팡에서 약 3만원에 팔아여!!,8,1,308
...,...,...,...,...,...,...,...,...,...,...
3062,227023392,양천구 신정동,“빛나는 생일보내” 스틸라 리퀴드섀도우 선물세트 키튼카르마 미니팁 ( 언더 반짝이 펄),뷰티/미용,끌올 3일 전,19000,새거입니당 \n선물박스포장그대로있어요,2,1,175
3063,292599855,양천구 신정3동,볼빅 골프공 선물셋트(마크포함),스포츠/레저,끌올 2일 전,18000,골프공 3개×2개 볼마크\n신기초등정문앞\n반품불가,0,0,271
3064,287567030,양천구 신월7동,명절선물 세트 스팸,생활/가공식품,끌올 6일 전,43000,명절때 받은 스팸이예요\n다른곳에서도 들어와서 많아요\n200g×16,5,1,850
3065,289625483,양천구 목3동,하이포크 새우젓으로 맛을 낸 햄 선물세트 팝니다,생활/가공식품,끌올 4일 전,22000,추석선물로 햄이 많이 들어와 팝니다\n사진 참고해주세요 박스 쇼핑백 다 상태 좋아요,1,0,133
3066,270978904,양천구 신월2동,양키캔들 6구 선물세트,뷰티/미용,끌올 3일 전,25000,미개봉 새제품입니다.\n쿨거래시 네고가능,1,0,41

In [390]:
df05['date'] = '211005'
df05['date']=pd.to_datetime(df05['date'], format="%y%m%d")
df05.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,284578634,동작구 흑석동,키엘 포맨 선물세트,남성패션/잡화,끌올 2일 전,45000,선물 받았는데 쓰는 제품이 있어서 판매합니다\n훼이셜 퓨얼 에너자이징 토닉250 ml\n모이스쳐라이져 트리트먼트 포 맨 75ml\n증정품2개,4,0,92,2021-10-05
1,291941854,동작구 사당동,뉴트리라이트 더블엑스 선물세트,생활/가공식품,끌올 4일 전,120000,본품1 리필1로 구성된 선물세트로 정가 167000원이네요\n명절선물로 받았는데 먹는 영양제가 많아 내놓아요\n뉴트리라이트 종이백도 같이있어 선물용으로도 좋아요 ^^\n아시는분들은 아시는 고급영양제 더블엑스 저렴하게 데려가세요,2,1,76,2021-10-05

In [391]:
df05.to_csv('./seoul_211005_date.csv',encoding='utf-8-sig')

## 1006

In [40]:
path = './전처리/1006/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

df06 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df06 = pd.concat([df06,data])
    
df06 = df06.reset_index(drop = True)
df06

,num,region,title,category,time,price,detail,interest,chat,view
0,287040785,용산구 이촌제1동,청정원 선물셋트 (스페셜1호),생활/가공식품,끌올 5일 전,27000,청정원 스페셜 1호 선물셋트 미개봉 새 제품입니다.\n이촌역에서 직거래 원합니다.,1,2,173
1,293579864,용산구 산천동,추석 선물세트,생활/가공식품,끌올 1일 전,50000,추석선물세트(미개봉) 모두 하시면 일괄 5만원에 다 드리겠습니다 상세설명은 판매페이지 보시면 각각 올려놓았습니다 참고바랍니다 직거래는 성심여고후문입니다,4,0,216
2,286815133,용산구 동빙고동,💥안상규💥 벌꿀 허니영 선물 세트 새상품💥세계대회 대상 꿀,생활/가공식품,끌올 3일 전,40000,선물 하시기 좋아요\n포장도 고급스러워요\n워낙 유명한 꿀이거든요\n사진으로 상세설명 확인하세요,6,0,205
3,284862337,용산구 이촌동,세인트나인 Q soft premium 골프공+골프티 선물세트(2박스 구입 가능),스포츠/레저,끌올 6일 전,15000,"세인트나인 골프공(6구)+골프티 세트 2박스입니다.\n한 박스는 내용물 확인하려고 포장지 벗겼는데 나머지 한 박스는 포장된 그대로입니다. \n1세트 15천원, 2세트 30천원에 판매 원합니다.",3,1,308
4,287916702,용산구 이촌동,자연을 품은 표고버섯 선물세트 미개봉 새제품 (선물가능),생활/가공식품,끌올 11일 전,35000,마수아 표고버섯 선물세트 \n혼합버섯세트4호\n포장 뜯지않은 새제품으로 선물용으로 가능합니다.,4,3,197
...,...,...,...,...,...,...,...,...,...,...
3060,288339925,서대문구 연희동,cj 햄선물세트 N호,생활/가공식품,끌올 11일 전,20000,햄선물 세트 팝니다.\n선물받았는데 많아서\n저렴하게 팝니다\n필요하신분 가져가세요\n인터넷에 28.900원 입니다\n유통기한 23년 3월 1일까지입니댜,6,6,610
3061,287635172,서대문구 홍제제3동,"암웨이 뉴트리라이트 베스트 선물세트(더블엑스, 오메가)",생활/가공식품,끌올 2일 전,90000,암웨이 더블엑스 오메가 선물세트 판매합니다\n택배 요청 가능!,3,6,386
3062,285957889,서대문구 홍제제1동,설화수 선물세트+쇼핑백,뷰티/미용,끌올 2일 전,67000,설화수 자음수 자음액 세트(~24.04까지)\n전용 쇼핑백도 같이 드립니다. 선물용으로 좋아요.\n직거래 무악재역,24,1,207
3063,292458669,서대문구 남가좌동,록시땅 핸드크림 립밤 선물세트,뷰티/미용,7일 전,7000,새제품\n포장상태\ndmc에코자이 문고리거래원해요,0,1,39
3064,290430357,서대문구 북가좌제2동,CJ 현명한 선택 H호 선물세트팝니다,생활/가공식품,끌올 4일 전,19000,추석에 선물받은 선물세트팝니다\nCJ 현명한 선택 H호\n한번뜯어보기만했어요 \n쇼핑백도 같이드립니다,1,0,143

In [41]:
df06['date'] = '211006'
df06['date']=pd.to_datetime(df06['date'], format="%y%m%d")
df06.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,287040785,용산구 이촌제1동,청정원 선물셋트 (스페셜1호),생활/가공식품,끌올 5일 전,27000,청정원 스페셜 1호 선물셋트 미개봉 새 제품입니다.\n이촌역에서 직거래 원합니다.,1,2,173,2021-10-06
1,293579864,용산구 산천동,추석 선물세트,생활/가공식품,끌올 1일 전,50000,추석선물세트(미개봉) 모두 하시면 일괄 5만원에 다 드리겠습니다 상세설명은 판매페이지 보시면 각각 올려놓았습니다 참고바랍니다 직거래는 성심여고후문입니다,4,0,216,2021-10-06

In [42]:
df06.to_csv('./전처리/seoul/seoul_211006_date.csv',encoding='utf-8-sig')

## 1007

In [36]:
path = './전처리/1007/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

df07 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df07 = pd.concat([df07,data])
    
df07 = df07.reset_index(drop = True)
df07

,num,region,title,category,time,price,detail,interest,chat,view
0,295481114,양천구 신정4동,스팸 오일 선물세트,생활/가공식품,1일 전,8000,이번 추석 선물로 들어온 건데\n너무 많아 내놓습니다.,4,3,73
1,282682808,양천구 목1동,록시땅 핸드크림 3개 선물셋트,뷰티/미용,끌올 3일 전,30000,선물 받았으나 제가 쓰는 제품이 아니라 내놓습니다~\n쇼핑백도 있어요~\n30ml 3개 입니다~,5,1,156
2,286135340,양천구 신월동,스네일 달팽이 남성 기초화장품 선물세트 추석선물,뷰티/미용,끌올 1일 전,15000,"직거래, 택배가능\n문의주세요",12,3,416
3,294160317,양천구 목동,리챔 선물셋트 15000원,생활/가공식품,4일 전,15000,쇼핑백도 있어요~~ 유통기한도 넉넉합니다~~,0,3,115
4,292719408,양천구 신정4동,고헌정선물셋트1호,생활/가공식품,끌올 18시간 전,15000,"고헌정선물세트1호\n구성: 동학 375mlX4개, 요정맛술 250mlX1병(유통기한:제조일로 2년)제조일:20년 7월",2,0,89
...,...,...,...,...,...,...,...,...,...,...
3042,295232676,강남구 대치1동,샹달프 잼 5종 선물셋트,생활/가공식품,1일 전,20000,추석에 선물받은 샹달프 잼 5종 셋트 팔아요.\n아이들이 밥을 좋아해 잼은 잘 안먹게 되네요.,13,0,225
3043,295408955,강남구 삼성동,비오템 핸드크림 + 립밤 선물 세트,뷰티/미용,1일 전,33000,비오템 립밤 핸드크림 선물 받았는데 저렴하게 판매합니다~,0,0,15
3044,294029609,강남구 역삼동,소고기 육포 선물세트,생활/가공식품,끌올 2일 전,70000,미소어육 국내산 소고기 육포입니다\n인터넷 판매가 10만원 넘습니다\n유통기한 22. 08\n쇼핑백 있습니다,6,0,165
3045,281522617,강남구 압구정동,"[연말 선물] YUNJAC 연작 화장품 선물셋트(정품, 미개봉)",뷰티/미용,끌올 2일 전,190000,신세계 백화점에 있는 요즘 워낙 유명한 고급화장품 YUNJAC 연작 선물셋트 저렴하게 올립니다^^,14,0,532
3046,295615938,강남구 삼성1동,'후'화장품 백화점 선물세트,뷰티/미용,19시간 전,100000,롯데백화점 분당점 제품이고 \n선물세트165000원에 \n현재 판매중인 제품입니다. \n유통기한 2024.7월~8월\n상품 특성상 깨질 위험이 있어 \n직거래로만 가능합니다.,4,0,69

In [37]:
df07['date'] = '211007'
df07['date']=pd.to_datetime(df07['date'], format="%y%m%d")
df07.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,295481114,양천구 신정4동,스팸 오일 선물세트,생활/가공식품,1일 전,8000,이번 추석 선물로 들어온 건데\n너무 많아 내놓습니다.,4,3,73,2021-10-07
1,282682808,양천구 목1동,록시땅 핸드크림 3개 선물셋트,뷰티/미용,끌올 3일 전,30000,선물 받았으나 제가 쓰는 제품이 아니라 내놓습니다~\n쇼핑백도 있어요~\n30ml 3개 입니다~,5,1,156,2021-10-07

In [39]:
df07.to_csv('./전처리/seoul/seoul_211007_date.csv',encoding='utf-8-sig')

## 1008

In [3]:
path = './전처리/1008/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.xlsx')]

df08 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_excel(path+i)
    df08 = pd.concat([df08,data])
    
df08 = df08.reset_index(drop = True)
df08

,num,region,title,category,time,price,detail,interest,chat,view
0,250653769,은평구 갈현제2동,명절선물 엘지생활선물세트 생활의기쁨 37호팝니다,뷰티/미용,끌올 8일 전,20000,엘지생활선물세트 생활의기쁨 37호\n팝니다 새상품 이구요\n유통기한23년 까지입니다...,8,1,258
1,286577302,은평구 불광동,암웨이 퍼스널케어 선물세트 (새상품),뷰티/미용,끌올 2일 전,40000,암웨이 퍼스널케어 선물세트 미개봉 새상품입니다. 유통기한 넉넉하고 외관 깨끗하여 선...,5,3,233
2,248555700,은평구 대조동,새상품)압소바 딸랑이 선물세트,유아동,끌올 4일 전,17000,\n문고리거래희망\n@연신내 뚜레쥬르 근처,18,2,467
3,286263642,은평구 녹번동,추석 선물 세트 - 샴푸 세제 등,생활/가공식품,끌올 15분 전,24000,오늘 받은 추석 선물 세트 팔아요.,2,3,422
4,287121035,은평구 갈현제1동,프리미엄 참기름 들기름 선물세트 쿠엔즈버킷,생활/가공식품,끌올 2일 전,43000,"쿠엔즈 버킷 참들들 선물세트입니다.\n패키지가 아주 고급스럽기도 하고, 원래도 프리...",8,0,338
...,...,...,...,...,...,...,...,...,...,...
3074,292126414,관악구 봉천동,"오늘까지❤미개봉상품❤음양오행 건강선물세트 , 음료세트",생활/가공식품,끌올 3일 전,8000,"*미개봉 선물세트, 2022.04.26 까지\n*쑥고개성당 직거래 가능\n*교환,환불×",2,0,183
3075,286096233,관악구 성현동,베이비 베이커리 오르골 딸랑이 아기 신발 턱받이 세트 (새상품) 출산선물,유아동,끌올 3일 전,25000,(운영 정책에 의한 URL 자동 숨김),11,0,449
3076,290070686,관악구 미성동,리챔 6호 선물세트 팝니다,생활/가공식품,끌올 1일 전,15000,200g 9개입니다!\n신대방역/신림역 직거래가능합니다,7,3,427
3077,291149769,관악구 신림동,스팸1호선물세트,생활/가공식품,끌올 3일 전,40000,"똑같은 스팸세트가 두개 들어와 하나는 저렴하게 내놓습니다\n원정가 59,210원 입...",5,2,365
3078,292400955,관악구 신림동,밀크바오밥 바디워시 1L 바디로션500ml 선물세트 (손잡이박스),뷰티/미용,끌올 15시간 전,18000,"밀크바오밥 바디워시 1000ml, 바디로션 500ml\n선물세트 판매합니다.\n유효...",6,0,128

In [4]:
df08['date'] = '211008'
df08['date']=pd.to_datetime(df08['date'], format="%y%m%d")
df08.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date
0,250653769,은평구 갈현제2동,명절선물 엘지생활선물세트 생활의기쁨 37호팝니다,뷰티/미용,끌올 8일 전,20000,엘지생활선물세트 생활의기쁨 37호\n팝니다 새상품 이구요\n유통기한23년 까지입니다...,8,1,258,2021-10-08
1,286577302,은평구 불광동,암웨이 퍼스널케어 선물세트 (새상품),뷰티/미용,끌올 2일 전,40000,암웨이 퍼스널케어 선물세트 미개봉 새상품입니다. 유통기한 넉넉하고 외관 깨끗하여 선...,5,3,233,2021-10-08

In [5]:
df08.to_csv('./전처리/seoul/seoul_211008_date.csv',encoding='utf-8-sig')

## 전체 전처리

In [6]:
path = './전처리/seoul/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')]

df = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(path+i)
    df = pd.concat([df,data])
    
df = df.reset_index(drop = True)
df = df.drop(['Unnamed: 0'],axis=1)
df

,num,region,title,category,time,price,detail,interest,chat,view,date
0,250653769,은평구 갈현제2동,명절선물 엘지생활선물세트 생활의기쁨 37호팝니다,뷰티/미용,끌올 8일 전,20000,엘지생활선물세트 생활의기쁨 37호\n팝니다 새상품 이구요\n유통기한23년 까지입니다...,8,1,258,2021-10-08
1,286577302,은평구 불광동,암웨이 퍼스널케어 선물세트 (새상품),뷰티/미용,끌올 2일 전,40000,암웨이 퍼스널케어 선물세트 미개봉 새상품입니다. 유통기한 넉넉하고 외관 깨끗하여 선...,5,3,233,2021-10-08
2,248555700,은평구 대조동,새상품)압소바 딸랑이 선물세트,유아동,끌올 4일 전,17000,\n문고리거래희망\n@연신내 뚜레쥬르 근처,18,2,467,2021-10-08
3,286263642,은평구 녹번동,추석 선물 세트 - 샴푸 세제 등,생활/가공식품,끌올 15분 전,24000,오늘 받은 추석 선물 세트 팔아요.,2,3,422,2021-10-08
4,287121035,은평구 갈현제1동,프리미엄 참기름 들기름 선물세트 쿠엔즈버킷,생활/가공식품,끌올 2일 전,43000,"쿠엔즈 버킷 참들들 선물세트입니다.\n패키지가 아주 고급스럽기도 하고, 원래도 프리...",8,0,338,2021-10-08
...,...,...,...,...,...,...,...,...,...,...,...
38916,288339925,서대문구 연희동,cj 햄선물세트 N호,생활/가공식품,끌올 11일 전,20000,햄선물 세트 팝니다.\n선물받았는데 많아서\n저렴하게 팝니다\n필요하신분 가져가세요...,6,6,610,2021-10-06
38917,287635172,서대문구 홍제제3동,"암웨이 뉴트리라이트 베스트 선물세트(더블엑스, 오메가)",생활/가공식품,끌올 2일 전,90000,암웨이 더블엑스 오메가 선물세트 판매합니다\n택배 요청 가능!,3,6,386,2021-10-06
38918,285957889,서대문구 홍제제1동,설화수 선물세트+쇼핑백,뷰티/미용,끌올 2일 전,67000,설화수 자음수 자음액 세트(~24.04까지)\n전용 쇼핑백도 같이 드립니다. 선물용...,24,1,207,2021-10-06
38919,292458669,서대문구 남가좌동,록시땅 핸드크림 립밤 선물세트,뷰티/미용,7일 전,7000,새제품\n포장상태\ndmc에코자이 문고리거래원해요,0,1,39,2021-10-06
38920,290430357,서대문구 북가좌제2동,CJ 현명한 선택 H호 선물세트팝니다,생활/가공식품,끌올 4일 전,19000,추석에 선물받은 선물세트팝니다\nCJ 현명한 선택 H호\n한번뜯어보기만했어요 \n쇼...,1,0,143,2021-10-06

In [7]:
df['gu'] = df['region'].str.split(' ',expand=True)[0]
df['dong'] = df['region'].str.split(' ', expand=True)[1]
df.head(2)

,num,region,title,category,time,price,detail,interest,chat,view,date,gu,dong
0,250653769,은평구 갈현제2동,명절선물 엘지생활선물세트 생활의기쁨 37호팝니다,뷰티/미용,끌올 8일 전,20000,엘지생활선물세트 생활의기쁨 37호\n팝니다 새상품 이구요\n유통기한23년 까지입니다...,8,1,258,2021-10-08,은평구,갈현제2동
1,286577302,은평구 불광동,암웨이 퍼스널케어 선물세트 (새상품),뷰티/미용,끌올 2일 전,40000,암웨이 퍼스널케어 선물세트 미개봉 새상품입니다. 유통기한 넉넉하고 외관 깨끗하여 선...,5,3,233,2021-10-08,은평구,불광동

In [65]:
df.gu[[25685]]

25685    성북구
Name: gu, dtype: object

In [12]:
df.to_csv('./전처리/seoul_date_211008_중복제거X.csv',encoding='utf-8-sig')

In [13]:
df.to_excel('./전처리/seoul_date_211008_중복제거X.xlsx',encoding='utf-8-sig')

In [43]:
32795 + 3047

35842

In [63]:
df['gu'].unique()

array(['관악구', '중랑구', '서대문구', '강서구', '송파구', '구로구', '광진구', '서초구', '도봉구',
       '성동구', '강남구', '은평구', '중구', '노원구', '강동구', '영등포구', '금천구', '양천구',
       '동작구', '용산구', '마포구', '종로구', '동대문구', '강북구', '성북구'], dtype=object)

In [64]:
df['dong'].unique()

array(['봉천동', '신원동', '서원동', '신림동', '은천동', '신사동', '난곡동', '청룡동', '행운동',
       '남현동', '인헌동', '청림동', '대학동', '중앙동', '보라매동', '성현동', '낙성대동', '조원동',
       '미성동', '난향동', '서림동', '중화동', '면목본동', '묵동', '상봉동', '중화제1동', '상봉제2동',
       '신내2동', '망우동', '면목제2동', '면목동', '신내동', '상봉제1동', '신내1동', '면목제7동',
       '묵제1동', '망우제3동', '망우본동', '묵제2동', '중화제2동', '면목제3.8동', '연희동', '창천동',
       '북아현동', '현저동', '홍제제3동', '홍은동', '북가좌동', '충정로3가', '옥천동', '홍은제1동',
       '홍제제1동', '홍제동', '대현동', '북가좌제2동', '북가좌제1동', '신촌동', '홍은제2동', '충현동',
       '남가좌동', '충정로2가', '천연동', '남가좌제1동', '대신동', '남가좌제2동', '방화제1동',
       '화곡제1동', '화곡동', '마곡동', '염창동', '내발산동', '등촌동', '등촌제3동', '방화동',
       '화곡본동', '화곡제3동', '방화제2동', '발산제1동', '가양동', '화곡제6동', '가양제3동',
       '화곡제4동', '등촌제1동', '등촌제2동', '우장산동', '화곡제2동', '공항동', '석촌동', '잠실7동',
       '문정2동', '거여2동', '잠실2동', '위례동', '잠실3동', '가락동', '문정동', '방이2동', '삼전동',
       '잠실본동', '가락2동', '송파동', '가락1동', '오금동', '송파2동', '문정1동', '풍납2동',
       '장지동', '거여동', '방이동', '잠실동', '잠실6동', '풍납동', '잠실4동', '거여1동', '송파1동',
       '신천동', '구로동', '개봉제3동', '오류동', '온수동', '개봉제1동', '구로제3동', '고척동',
       '구로제2동', '구로제5동', '수궁동', '오류제1동', '신도림동', '항동', '천왕동', '개봉동',
       '오류제2동', '개봉제2동', '구로제1동', '고척제2동', '궁동', '고척제1동', '구로제4동', '자양동',
       '구의제1동', '구의제3동', '화양동', '구의동', '중곡제2동', '능동', '군자동', '중곡제4동',
       '구의제2동', '자양제2동', '자양제3동', '자양제1동', '중곡동', '광장동', '중곡제3동', '중곡제1동',
       '자양제4동', '서초2동', '서초동', '반포3동', '잠원동', '방배본동', '내곡동', '서초4동',
       '방배동', '우면동', '반포4동', '양재동', '방배3동', '반포2동', '반포동', '방배4동', '서초1동',
       '반포본동', '서초3동', '방배2동', '반포1동', '방배1동', '양재1동', '양재2동', '창동',
       '도봉동', '도봉제1동', '쌍문제4동', '방학제1동', '창제5동', '도봉제2동', '쌍문동', '창제1동',
       '방학동', '창제2동', '방학제3동', '쌍문제2동', '방학제2동', '창제4동', '창제3동', '쌍문제1동',
       '마장동', '상왕십리동', '금호동1가', '성수1가제2동', '금호1가동', '성수동2가', '금호동3가',
       '도선동', '응봉동', '성수동1가', '행당동', '금호동2가', '하왕십리동', '성수2가제3동',
       '왕십리제2동', '금호4가동', '성수1가제1동', '옥수동', '성수2가제1동', '행당제2동', '용답동',
       '행당제1동', '금호2.3가동', '금호동4가', '왕십리도선동', '사근동', '논현동', '논현2동',
       '삼성1동', '수서동', '개포4동', '역삼동', '대치동', '도곡1동', '역삼1동', '대치1동',
       '일원본동', '개포동', '대치4동', '청담동', '논현1동', '삼성동', '도곡동', '도곡2동', '자곡동',
       '압구정동', '일원동', '일원2동', '세곡동', '삼성2동', '역삼2동', '대치2동', '응암동',
       '신사제1동', '불광제1동', '역촌동', '진관동', '구산동', '대조동', '녹번동', '불광동',
       '응암제2동', '갈현제2동', '응암제1동', '수색동', '갈현제1동', '불광제2동', '증산동', '갈현동',
       '응암제3동', '신사제2동', '부사동', '태평2동', '산성동', '문화동', '용두동', '문화1동',
       '태평1동', '안영동', '태평동', '대흥동', '은행선화동', '선화동', '문화2동', '석교동', '문창동',
       '목동', '유천동', '대사동', '사정동', '중촌동', '유천1동', '유천2동', '은행동', '중계2.3동',
       '상계8동', '하계2동', '공릉2동', '중계동', '공릉동', '상계2동', '상계동', '월계동', '상계9동',
       '월계3동', '하계동', '중계4동', '월계2동', '중계본동', '공릉1동', '상계1동', '상계6.7동',
       '상계3.4동', '중계1동', '상계5동', '하계1동', '월계1동', '상계10동', '고덕제1동', '천호동',
       '길동', '명일제2동', '명일동', '천호제1동', '고덕제2동', '강일동', '상일동', '암사제2동',
       '둔촌제2동', '암사제1동', '성내제3동', '성내동', '암사제3동', '둔촌동', '명일제1동', '성내제1동',
       '암사동', '천호제2동', '성내제2동', '고덕동', '문래동3가', '영등포동7가', '신길동', '당산동4가',
       '양평동2가', '신길제6동', '대림제2동', '여의도동', '문래동2가', '대림제1동', '영등포동4가',
       '당산동1가', '영등포동5가', '영등포동8가', '영등포본동', '신길제1동', '대림동', '양평제1동',
       '문래동6가', '여의동', '양평동1가', '도림동', '영등포동3가', '문래동', '양평동4가', '당산동6가',
       '양평제2동', '당산동5가', '신길제7동', '당산동2가', '당산동3가', '양평동3가', '당산동',
       '신길제3동', '대림제3동', '당산제2동', '영등포동1가', '양평동5가', '가산동', '시흥동',
       '독산제3동', '독산동', '시흥제4동', '시흥제3동', '시흥제1동', '시흥제2동', '독산제1동',
       '독산제2동', '독산제4동', '신월2동', '신월7동', '목5동', '신정7동', '신월동', '신월6동',
       '목4동', '신정1동', '신정4동', '목2동', '신정2동', '신정6동', '신정동', '신정3동',
       '신월5동', '신월1동', '목3동', '목1동', '신월3동', '신월4동', '상도동', '대방동', '노량진동',
       '노량진제1동', '사당동', '사당제5동', '사당제1동', '사당제2동', '상도제3동', '본동',
       '노량진제2동', '동작동', '사당제3동', '신대방동', '흑석동', '상도제1동', '신대방제2동',
       '상도제2동', '상도1동', '사당제4동', '상도제4동', '한강로2가', '동자동', '한강로1가', '한남동',
       '이촌동', '도원동', '이태원동', '용산동2가', '이촌제1동', '동빙고동', '후암동', '원효로1가',
       '원효로제1동', '산천동', '한강로3가', '청파동', '용문동', '용산동3가', '이태원제2동', '한강로동',
       '원효로제2동', '용산동6가', '청파동1가', '서계동', '보광동', '이태원제1동', '효창동', '원효로3가',
       '갈월동', '청파동3가', '서빙고동', '용산동1가', '용산동5가', '신계동', '남영동', '망원동',
       '아현동', '공덕동', '합정동', '상수동', '신수동', '망원제1동', '연남동', '창전동', '상암동',
       '성산제1동', '성산동', '서교동', '서강동', '신공덕동', '성산제2동', '동교동', '토정동', '염리동',
       '도화동', '노고산동', '용강동', '중동', '혜화동', '삼청동', '원서동', '숭인동', '관수동',
       '창신동', '홍파동', '명륜2가', '동숭동', '평창동', '교남동', '창신제2동', '익선동', '창신제3동',
       '신문로1가', '무악동', '연지동', '평동', '계동', '옥인동', '세종로', '교북동', '이화동',
       '통인동', '공평동', '청운효자동', '내수동', '명륜4가', '종로1.2.3.4가동', '사직동',
       '숭인제2동', '명륜1가', '행촌동', '수송동', '당주동', '종로1가', '연건동', '청진동', '가회동',
       '신문로2가', '중학동', '송현동', '신영동', '구기동', '적선동', '인의동', '종로2가', '효자동',
       '서린동', '청량리동', '이문동', '장안제2동', '전농제1동', '답십리동', '장안동', '전농동',
       '제기동', '용신동', '장안제1동', '답십리제1동', '회기동', '휘경동', '이문제2동', '휘경제2동',
       '전농제2동', '답십리제2동', '신설동', '휘경제1동', '번동', '수유동', '미아동', '번1동',
       '우이동', '수유1동', '수유2동', '삼각산동', '송중동', '송천동', '수유3동', '인수동', '번2동',
       '번3동', '삼양동', '월곡제2동', '종암동', '동소문동6가', '길음동', '하월곡동', '장위동',
       '보문동6가', '안암동', '돈암동', '성북동', '정릉제4동', '정릉제3동', '장위제3동', '상월곡동',
       '석관동', '정릉동', '정릉제2동', '삼선동2가', '동선동', '삼선동3가', '돈암제1동', '길음제2동',
       '삼선동', '보문동4가', '정릉제1동', '장위제1동', '동선동2가', '안암동1가', '동소문동4가',
       '성북동1가', '돈암제2동', '보문동2가', '길음제1동', '삼선동1가', '망원제2동', '마포동',
       '홍제제2동', '신길제5동', '영등포동', '신길제4동', '원효로2가', '문배동', '원효로4가', '개포2동',
       '일원1동', '풍납1동', '오륜동', '가락본동', '마천1동', '방이1동', '마천동', '동선동4가',
       '문래동4가', '송정동', '방화제3동', '가양제1동', '시흥제5동', '신대방제1동', '가양제2동',
       '현석동', '보문동7가', '안암동5가', '양평동6가', '면목제4동', '가리봉동', '송월동', '누상동',
       '홍지동', '삼선동5가', '보문동', '월곡제1동', '필운동', '종로5.6가동', '신교동', '명륜3가',
       '통의동', '재동', '효제동', '부암동', '관훈동', '종로6가', '안국동', '종로3가', '홍익동',
       '옥계동', '영등포동2가', '당산제1동', '면목제5동', '쌍문제3동', '신창동', '동선동3가',
       '천호제3동', '마천2동', '영천동', '미근동', '화곡제8동', '율현동', '영등포동6가', '청암동',
       '동선동5가'], dtype=object)

In [11]:
df[df['gu']=='안암동'].index

Int64Index([], dtype='int64')

In [9]:
df['dong'][[15420, 15432, 15474, 20117, 24281, 24285, 24426, 28731, 28734,28764]] = '안암동'

<ipython-input-9-30c283bead22>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dong'][[15420, 15432, 15474, 20117, 24281, 24285, 24426, 28731, 28734,28764]] = '안암동'

In [10]:
df['gu'][[15420, 15432, 15474, 20117, 24281, 24285, 24426, 28731, 28734,28764]] = '성북구'

<ipython-input-10-9d5753407941>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gu'][[15420, 15432, 15474, 20117, 24281, 24285, 24426, 28731, 28734,28764]] = '성북구'